maybe more changes (untested)

diff --git a/setup/bootstrap b/setup/bootstrap
--- a/setup/bootstrap
+++ b/setup/bootstrap
@@ -3,7 +3,7 @@
 TEMP_D=""
 
 fail() { echo "$@" 1>&2; exit 1; }
-cleanup() { 
+cleanup() {
   rm -Rf "$TEMP_D"
 }
 
@@ -12,7 +12,7 @@ h=${1:-$HOME}
 TEMP_D=$(mktemp -d) || exit
 trap cleanup EXIT
 
-( 
+(
   cd "$TEMP_D" &&
   git clone "$gittilda" tilda &&
   cd tilda && sudo ./setup/system
@@ -29,22 +29,6 @@ fi
 
 mkdir -p "$h/bin" || exit 1
 ( ln -svf tilda/dotfiles/.[a-zA-Z]* . ) || exit 1
-
 ( cd "$h/bin" && ln -svf ../tilda/bin/* . ) || exit 1
 
-. "$h/.profile.local" || exit 1
-
-( cd "$h/tilda" && ./setup/chainguard ) || fail "setup/chainguard failed"
-
-cd "$h/bin" || exit 1
-for f in ../gists/*/*; do
-    [ -f "$f" -a -x "$f" ] || continue;
-    ln -svf "$f" . || exit 1
-done
-
-mkdir -p "$h/src"
-
-echo "running vim pluginstall"
-vim +'PlugInstall --sync' +qa
-
-echo "all done happy time"
+( cd "$h/tilda" && ./setup/user ) || fail "setup/user failed"
